### ISSUE TITLE
additional feature that would be great

### ISSUE THREAD

**Issue by MehdiMamas** [fknives/Android-App-TikTok-Downloader#12]
Could you please make it whenever we click the share to app, it will download and open the app, currently when clicking that button it only downloads the video, but it does't open the app...
 thank you

**Comment by fknives** [comment]
Hey, thanks for the feedback, I have uploaded a new apk and you may check the source code changes.

Hopefully I understood your request properly, here is a video showcasing the new functionality:
https://youtube.com/shorts/zdUHIRzJxCc?feature=share
(for some reason its a shorts, its less than a minute tho)

Feel free to download the new apk directly or via the same QR code, hope this helps.

**Comment by MehdiMamas** [comment]
Yes, Perfect, thank you for the update
