### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by mathe00** [fknives/Android-App-TikTok-Downloader#13]
It is impossible for me to download any Tiktok video since some time (beginning of the month I would say). I think Tiktok has changed some things in the process of downloading videos, but I'm not sure, I didn't really look for it.

I have the error: Parsing Error

**Comment by fknives** [comment]
@mathe00 Hello, I actually have a running pipeline to check if the download process is still works as intended [here](https://github.com/fknives/TikTok-Downloader/actions/runs/4075039208/jobs/7020914798), last ran 1 hour ago.
According to that and testing on my own device, the download is still working.

Could you maybe give me a TikTok URL you are trying to download?

It is possible for example that one of the videos have been deleted and it tries to download that first (and fails) and never gets to the second in the queue.
In such a case one can just swipe away the first video, retry and it shall start downloading the now became first video.

**Comment by mathe00** [comment]
> @mathe00 Hello, I actually have a running pipeline to check if the download process is still works as intended [here](https://github.com/fknives/TikTok-Downloader/actions/runs/4075039208/jobs/7020914798), last ran 1 hour ago. According to that and testing on my own device, the download is still working.
> 
> Could you maybe give me a TikTok URL you are trying to download?
> 
> It is possible for example that one of the videos have been deleted and it tries to download that first (and fails) and never gets to the second in the queue. In such a case one can just swipe away the first video, retry and it shall start downloading the now became first video.

That must have been what you told me. I reinstalled the app just now and it seems to be working again, yet it seemed to have done so when I had the problem the first time. 

Thanks!
