### ISSUE TITLE
Video Link Parsing

### ISSUE THREAD

**Issue by CovenantJunior** [fknives/Android-App-TikTok-Downloader#2]
Video link isn't parsing after START button is clicked

**Comment by fknives** [comment]
@CovenantJunior hey, thanks for the notice! Sadly the project got a bit down on priority, But I will get back to it sometime soon and will take a look.

**Comment by CovenantJunior** [comment]
> @CovenantJunior hey, thanks for the notice! Sadly the project got a bit down on priority, But I will get back to it sometime soon and will take a look.

Alright, that'll be great! 🙂

**Comment by fknives** [comment]
Should be fixed with PR #3.
A new APK has been uploaded that can be downloaded via the QR code

**Comment by CovenantJunior** [comment]
Awesome, thanks!
